#!/usr/bin/env bash
#
# ------------------------------------------------------------------------------------ #
# bak_incremental: - Incremental backup for files from local directory to an External Device
#
# Author:        Gustavo Montenegro
# Maintenance:   Gustavo Montenegro
#
# ------------------------------------------------------------------------------------ #
# WHAT IT DOES?
# This script can be called by the normal way using "./" or scheduled to execute through Cron.
# You have to change the variables to point to your External Device.
#
# CONFIGURATION?
# I recommend you to create a softlink to folder that is available on $PATH variable.
# $ ln -s /backups/scripts/bak_incremetal /usr/local/bin
#
# HOW TO USE IT?
# Examples:
# $ ./bak_incremental.sh
#
# or
#
# 30 21 * * * root bak_incremental 1> /dev/null 2>&1
# ------------------------------------------------------------------------------------ #
# Changelog:
#
#   v1.0 16/08/2021, Gustavo Montenegro:
#     - First version with comments!
#
# ------------------------------------------------------------------------------------ #
# Tested on:
#   bash 5.1.4
# ------------------------------------------------------------------------------------ #

# --------------------------------- VARIABLES ---------------------------------------- #
# You can change
DEVICE="/dev/sdb1" # External Device (check with "fdisk -l")
SOURCE_DIR="/dir1/file1" # The directory where the backups files are stored
DESTINATION_DIR="/dir_backups/" # Mountpoint to your External Device
LOG_FILE="/backups/scripts/"bak_incremental_$(date --iso-8601=ns).log"" # The location from the log file
DATE='date --iso-8601=seconds'
# Don't Change
MOUNT_FILE="/proc/mounts"
NULL_DEVICE="1> /dev/null 2>&1"
REDIRECT_LOG_FILE="1>> $LOG_FILE 2>&1"
# ------------------------------------------------------------------------------------ #

# -------------------------------TESTS----------------------------------------- #
# Are you root?
[ "$UID" != "0" ] && {
  echo "---------- You must be root ----------" >> $LOG_FILE
  exit 1
}

# Is device mounted?
grep -q "$DEVICE" "$MOUNT_FILE"
if [ "$?" != "0" ]; then
  # If not, mount to $DESTINATION_DIR
  echo "---------- Device not mounted. Mounting $DEVICE ----------" >> $LOG_FILE
  eval mount "$DEVICE" "$DESTINATION_DIR" "$NULL_DEVICE"
else
  # If yes, grep the mount point and change the $DESTINATION_DIR
  DESTINATION_DIR=$(grep "$DEVICE" "$MOUNT_FILE" | cut -d " " -f 2)
fi

# Is there write permissions?
[ ! -w "$DESTINATION_DIR" ] && {
  echo "---------- Do not have write permissions ----------" >> $LOG_FILE
  exit 1
}
# ------------------------------------------------------------------------------------ #

# -------------------------------- FUNCTIONS ----------------------------------------- #
backup () {
  # Find the files with "find" command and copy only the differences (-u parameter from "cp" command)
  find "$SOURCE_DIR" -name "*.bak" \
                     -exec cp -vru {} "$DESTINATION_DIR" \; 1>> $LOG_FILE 2>&1
  # Worked fine? Umount.
  [ "$?" = "0" ] && {
    echo "---------- Back-up finished. Umounting $DEVICE ----------" >> $LOG_FILE
    eval umount "$DEVICE" "$NULL_DEVICE"
    exit 0
  }
}

preparelogfile () {
  # Insert a simple header to the log file with the timestamp
  echo "----------[ $DATE ]----------" >> $LOG_FILE
}

main () {
  preparelogfile
  backup
}
# ------------------------------------------------------------------------------------ #

# -------------------------------- EXECUTION ----------------------------------------- #
main
# ------------------------------------------------------------------------------------ #
